#ifndef RIKKI_PATCHER_RIKKI_E_DIR_HPP
#define RIKKI_PATCHER_RIKKI_E_DIR_HPP
#include "precompiled.hpp"

enum eDir : uint32_t {
    DIR_PROJ_BASE,
    DIR_PROJ_TEMP,

    DIR_PROJ_LANG,
    DIR_PROJ_CONFIG,
    DIR_PROJ_LOG,

    DIR_PROJ_DATA_EXTRACED,

    DIR_PROJ_EXE_7ZIP,

    DIR_GAME_BASE,
    DIR_GAME_FONTS,
    DIR_GAME_JSON_STARTUP,
    DIR_GAME_JSON_DIALOGUES
};


#endif //RIKKI_PATCHER_RIKKI_E_DIR_HPP
